apiVersion: v1
kind: Pod
metadata:
  name: victim-pod
spec:
  containers:
  - name: my-container
    image: diegoall1990/ubuntu-lab:1.0.0
    securityContext:
      privileged: true
      capabilities:
        add:
        - CAP_DAC_OVERRIDE
        - CAP_SYS_ADMIN
    stdin: true
    tty: true
    command: ["/bin/bash"]